### PR TITLE
Class codes

### PR DESCRIPTION
**Pull request by etotientz**
1st year undergrad RECursion class codes

### CODE REVIEW

**Comment by kumarneetesh24** [comment]
Please tell me what you did in commits so that it will be easy for me to add it.

**Comment by etotientz** [comment]
I have closed the pull request..The readme file can be edited a bit,if you suggest.

**Comment by etotientz** [comment]
and if possible our 1st yr Introduction ppt can be added too..

**Comment by kumarneetesh24** [comment]
Then do all the changes and push the changes. I have made you the owner of the repository. Now you can add everything you want.

**Comment by etotientz** [comment]
ok,thanks

**Pull request closed without merging**
